### ISSUE TITLE
建个gh-pages 我帮你生成这样的页面哦

### ISSUE THREAD

**Issue by jaywcjlove** [ecomfe/spec#15]
建个分支 gh-pages 弄个页面生成预览哦  [http://jaywcjlove.github.io/spec](http://jaywcjlove.github.io/spec)

**Comment by firede** [comment]
@jaywcjlove 谢谢你，不过不用啦。

非 jekyll 的静态生成工具需要额外进行 deploy，可能会导致两边的内容不同步。
我们还是遵循 KISS principle，直接在仓库看吧~
