### ISSUE TITLE
[esnext] 分号规则的问题

### ISSUE THREAD

**Issue by hax** [ecomfe/spec#17]
显见，全部加分号的规则，在esnext的情况下变得更加复杂——function声明，class声明，export声明，decorator，class properties等诸多例外，记忆负担很大。

建议采用 semicolon-less 风格，规则非常简单：不写分号，除非语句首是`[`、`(`，则在前面加分号。（正负号和正则literal等理论上可能产生歧义的符号通常不会出现在语句首。）

**Comment by sodatea** [comment]
只要编辑器用上 [FECS](http://fecs.baidu.com/) 插件，分号规则并没有什么记忆负担吧，这个应该主要是出于个人审美上的考虑。

**Comment by sodatea** [comment]
不过[属性装饰器部分](https://github.com/ecomfe/spec/blob/master/es-next-style-guide.md#user-content-强制-属性装饰器后可以不加分号的场景不允许加分号)要求尽可能不加分号，这个规则有点奇怪，与规范里其他部分提倡尽可能加分号的理念相左，而且与之前 [EFE 博客上的这篇文章](http://efe.baidu.com/blog/introduction-to-es-decorator/#几个坑)的推荐也相左。

**Comment by hax** [comment]
fecs是什么情况不太清楚，但是如果自己维护esnext语法解析，很可能还是会出问题的。最好的情况是假设fecs的质量相当于eslint。目前eslint, jscs等工具都已经支持传统分号写法和semicolon-free的coding style，甚至支持自动转换了。

不过再好的工具只是辅助，充其量让你更快建立起对某种coding style的条件反射。记忆负担仍然是存在的。尽管许多人觉得自己早已经记住了。（然而事实是否如此值得怀疑。且前面提到新增加的规则已经证明了负担还在加剧。）无论是集成在IDE中，还是额外的校验/转换步骤，只要是增加了错误可能，也就增加了对写代码的干扰。

当然，整体上，所有coding style，在有工具支持的情况下，选择某一种风格相对另一种的差异其实变得不那么重要了。所以在有足够好的工具支持下，选择都写分号也没那么糟。然而，既然要讨论coding style而不是随便拿一种过来用，则还是尽量考察实际在写代码中的利弊。就分号的例子，我不同意是出于“审美”。实际上有些人反对semicolon-free风格就是因为分号前置的例外规则“很丑”（尽管非常好记和实行）。

关于decorator，目前语法还没有最终定案。然而从现在的draft看，貌似是不能加分号的……不知道现在的规则是怎么来的。

**Comment by otakustay** [comment]
@hax 仅从ES6的角度来看，我觉得这个话题是很值得展开讨论的，但是作为一个在我厂内部已有规范的基础上作为addon而来的规范，这一点恐怕非常难变动

decorator的分号我们是用babel repl测出来的，现在来看只有一种情况是肯定需要分号的，即对应的method是一个computed property

**Comment by hax** [comment]
好的改变什么时候都不嫌晚，哈哈 :smiley_cat: 

尤其是在有自动转换工具可用的情况下，其实没有很大的变更成本。
而且在 ES3/5 => ESNEXT 这样大的升级的时候你还不做这种改变，将来就更没有机会变了。



decorator的computed property是draft语法本身有issue（https://github.com/wycats/javascript-decorators/issues/10），尚未确定最后的解决方案。但是加分号只是让parse不出错，其实并没有什么卵用。

目前有个很dirty的workaround是写成 get/set
```js
class A {
  @annotation get [...]() {...}
}
```

**Comment by errorrik** [comment]
1. 佛教徒和14蓝教徒是不可能说服对方的，除非物理消灭
2. 哪里都有江湖，都有规矩，我们其实也不可能在厂内其他所有语言都4空格时搞个2空格或tab出来

但无论如何，还是希望我们的规范能和同行一起完善，给一些借鉴。甚至其他团队其他公司有自己的code style，然后把其他的部分抄袭拿去用。这都是喜闻乐见的。

**Comment by hax** [comment]
我不同意coding style的争论是宗教问题。那个只是用来自嘲的，但是程序员讨论这些问题应该本着理性和实际的态度。
我也不同意多元化是主流，其实随着工具对多种coding style支持的提升，coding style倒是在明显的走向统一而不是分裂——最近的例子是 https://github.com/feross/standard 项目的出现。

因为工具的完善令转换成本变低了，然后交流变多了，反而有助于统一。（我们误解分歧多的一个可能的原因是原来对世界的认识太少，比如这里 https://en.wikipedia.org/wiki/Indent_style 的大部分缩进风格其实压根没见过。考虑这些风格现在都很少人用了，所以趋势是走向统一而不是多元。）

**Comment by errorrik** [comment]
对于任何一种语言，code style确实是统一的走向。但是如果语言设计时并未给出详尽的code style要求，在不同应用方中还是会形成两三种风格。另外不同语言之间的code style分歧从未停止。

所以，我更倾向于，尊重不同的公司、团队自己的风格，尊重他们的理由，尊重他们的历史（就算最终将消失）😄

**Comment by hax** [comment]
当然是必须尊重的，我也没法不尊重…… :astonished: 

然而我一直想吐槽的是：小小的coding style都改进不了，那还能指望更复杂的重构吗？ :stuck_out_tongue_winking_eye:

**Comment by errorrik** [comment]
其实我觉得改进code style比重构要难诶，毕竟通常你要重构一个东西，它是在你的power内的。而制订规范你无法保证不在你power内团队的执行。

我们在编制规范的过程，委员会明确的要求就是要考虑执行，引起所有团队反弹的事情肯定是执行不下去的。所以这个过程， @otakustay 也做了很多妥协。

基于此

1. 我们在code style相关的条目，基本是符合原有规范的，要不大家会说哎哟又来diao我了。我们也并不期望这种code style成为什么标杆，其他公司和团队各有各风格就挺好的。
2. guide相关的条目，我们就很open，因为只要条目本身合理，大家看了会觉得啊哈还挺有道理的，不会有逆反心理。

**Comment by hax** [comment]
我认为coding style当然要考虑执行，但是这个执行，是可执行性，比如工具支持，而不是单纯习惯性的反弹。

以分号规则而言，有一个很简单的办法：允许每个人使用不同的风格，但是用工具确保commit进repo的代码最后风格是semicolon-free的即可。这样的工具其实现在已经available了。

**Comment by errorrik** [comment]
讨论了下，这个事情看来不太可能实施，我就先关了。
