### ISSUE TITLE
[esnext] “不在直接声明的普通对象上使用装饰器”此条存疑

### ISSUE THREAD

**Issue by hax** [ecomfe/spec#22]
印象里decorator只支持class和method啊。（babel 6现在decorator转换挂了，所以没验证，悲剧。）

然而如果支持对一个对象上的method直接用decorator似乎也并没有理由禁止。

**Comment by otakustay** [comment]
从[babel repl](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=let%20o%20%3D%20%7B%0A%20%20%40foo%0A%20%20bar()%7B%7D%0A%7D)来看是可以的，包括在非方法的属性上使用也是可以的

对象直接量会使用在2种场景：

1. 一个带逻辑的对象，可能是一个模块的`export`
2. 一个纯对象，只是数据的

我们比较担心第2种情况下的滥用，在此先做比较严格的限制，在确定了一些实践的指导后再考虑改吧

**Comment by hax** [comment]
举个例子：
```
const o = {
  @nonenumerable test() {...}
}
```
这样的用途并没有什么不妥当啊。

**Comment by otakustay** [comment]
在方法上声明我觉得OK，但是在一个纯数据型的object上把装饰器丢property上我反对

这条可以改成**不得在对象的property上添加装饰器**？

**Comment by hax** [comment]
我就是写了：
```js
const test = {
  @readonly test: 'You should not change me!'
}
```
为什么不可以呢？

当然我理解作为data的plain object似乎应该保持简单，但是到底是不是plain object，这个不是检查能检查出来的呀。

**Comment by otakustay** [comment]
@errorrik 我想了一下，这条我们这么说不知是否合适

> 不在作为纯数据使用的对象上使用装饰器

这里需要对“纯数据”作一个定义，我理解是只承载属性且使用场景仅限于`hasOwnProperty`、`.foo`和`.foo = bar`、`for in`等对plain object的操作的

**Comment by hax** [comment]
@otakustay 然而我上面这个例子代码并不会影响它作为纯数据被使用。

担心被滥用，首先得有滥用的case，否则不清楚原因就禁止，以后可能会变成讲不清楚的历史遗留习惯。。。

**Comment by errorrik** [comment]
`纯数据`是一个很难被静态检查的定义诶。

decorator现在还不太成熟，我觉得这条不如暂时去掉，等看大家实践看看有没坑。对于这点，现在我没想出大家能玩出坑来，我甚至觉得大家应该都不会玩的。
