### ISSUE TITLE
[esnext] 不赞同“[建议] 使用 loose 生成更小、性能更高的代码”

### ISSUE THREAD

**Issue by hax** [ecomfe/spec#24]
相反，我认为如果没有benchmark证明产生了显著性能差异，应该避免用loose。

**Comment by sodatea** [comment]
支持 loose mode 的 transformer 也没几个……如果仔细看过文档的话，避开这些坑也不难。

不过根据 [Six Speed](https://kpdecker.github.io/six-speed/)，loose mode 下有显著性能差异的 ES6 特性只有 for-of-array、super 和 tagged template string 这几个。
所以我觉得更好的做法是，等 babel 6 稳定下来后，单独针对某个 transformer 配置 loose mode。

**Comment by hax** [comment]
“仔细看过文档”是一个不太靠谱的假设啊～

**Comment by otakustay** [comment]
这条是在babel还是5的时代下出来的，在babel6的情况下我们针对对应的transformer在性能出现问题时配就好了

**Comment by hax** [comment]
我的意思是你的应用没有benchmark证明某一点是性能瓶颈，则没有必要做这样的事情。

**Comment by errorrik** [comment]
@otakustay 我记得貌似内部讨论时说的是代码体积的问题而不是性能？

**Comment by otakustay** [comment]
是的，和代码体积有关，主要是`defineProperty`代替`prototype.xxx`以及`for .. of`的转换

**Comment by hax** [comment]
代码体积在gzip压缩之后应该并没有什么大差异吧

**Comment by errorrik** [comment]
@leeight 在项目里试试？

**Comment by otakustay** [comment]
我拿了2个项目试一下，基本gzip后差异在2.5%左右

不过确实我们没有大量使用`for .. of`这些东西，能`map`、`forEach`之类的就用上了

这种差异我认为是可以忽略的

**Comment by errorrik** [comment]
ok，并且loose在babel6里面已经不是个东西了。虽然6现在还坑不少，但是可预见很快会逐步填上。我觉得这条可以去掉， @otakustay 你觉得呢？

**Comment by otakustay** [comment]
这条就去掉吧
