### ISSUE TITLE
[esnext] 导出时不必用 const 定义

### ISSUE THREAD

**Issue by sodatea** [ecomfe/spec#26]
ES6 中， [imports 本来就是 immutable binding](http://exploringjs.com/es6/ch_modules.html#leanpub-auto-in-es6-imports-are-live-read-only-views-on-exported-values)，与 export 无关。

所以是否要用 `const` 定义应该根据程序本身的需求而定。

**Comment by hax** [comment]
我觉得此条或许应该改为：尽量避免导出mutable（let）。因为通常client users不会期待public api是可变的。尽管import本身应该是immutable binding，但是目前不能保证所有的实现都这样做（虽然babel是确保了的）。且用户还是可能自己创建 const x = ... 的副本。

**Comment by otakustay** [comment]
这个首先我的示例肯定是错的，我会改掉

但是导出还是应当尽量用`const`，外面用着用着就变掉了这是不合理的，且在非真正的ES6 module环境下我们实现的并不是binding的导出，这又会导致随module方案选择不同有不同的表现

**Comment by errorrik** [comment]
经讨论，决定删除此条

**Comment by errorrik** [comment]
一部分原因是，我们并不要求prefer-const，此处也无需const
