### ISSUE TITLE
请问markdown的目录树是怎么生成的？

### ISSUE THREAD

**Issue by git-lt** [ecomfe/spec#31]
请问markdown的目录树是怎么生成的？

**Comment by Vhyn** [comment]
在github的markdown支持中没有[Toc]

所以目录树需要用一个笨办法写

```
[123](## 123)
[456](## 456)
　　[6.1](### 6.1)

## 123
testtesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttest

## 456
testtesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttest

### 6.1
testtesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttest

```

效果是这样的

[123](## 123)
[456](## 456)
　　[6.1](### 6.1)

## 123
testtesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttest

## 456
testtesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttest

### 6.1
testtesttesttesttesttesttesttesttesttest
testtesttesttesttesttesttesttesttesttest

**Comment by errorrik** [comment]
自己写个脚本生成的
