### ISSUE TITLE
React 规范中无状态函数组件书写形式问题

### ISSUE THREAD

**Issue by chriswong** [ecomfe/spec#37]
> 对于直接return的函数组件，可以直接使用括号而省去大括号和return关键字：
>
> ```javascript
> let Message = () => (
>     <div>
>         <span>Hello World</span>
>     </div>
> );
> ```

Airbnb 的 React 规范中不推荐箭头函数的方式：
https://github.com/airbnb/javascript/tree/master/react#class-vs-reactcreateclass-vs-stateless
> And if you don't have state or refs, prefer normal functions (not arrow functions) over classes:
> 
> ```javascript
> // bad
> class Listing extends React.Component {
>   render() {
>     return <div>{this.props.hello}</div>;
>   }
> }
> 
> // bad (relying on function name inference is discouraged)
> const Listing = ({ hello }) => (
>   <div>{hello}</div>
> );
> 
> // good
> function Listing({ hello }) {
>   return <div>{hello}</div>;
> }
> ```

**Comment by otakustay** [comment]
当前支持箭头函数的`name`属性的浏览器是：

- Chrome 51+
- Firefox 53+

其它浏览器均不支持，使用babel可以让箭头函数具有名字（编译为`function Listing() ...`

规范倒也没有强制使用箭头函数，但也没有推荐或强制使用普通函数，我的理由是：

1. 希望尽可能多的函数是以箭头函数的形式出现。在高阶函数的情况下箭头函数拥有更好的可读性，而react由于提倡函数式因此高阶函数必然会出现，在这一点上使尽可能多的函数保持一个一致的风格有所收益
2. 可以在某些情况下省去`return`使得代码更为紧凑
3. 反正大家都是用babel编译到普通函数的，暂时没有发现不打开es2015 preset的情况

**Comment by otakustay** [comment]
另外我打算写一个babel插件，作用就是给“PascalCase命名”且“body含有JSX表达式”的箭头函数补一个`displayName`上去
