### ISSUE TITLE
react的eslint规则配置

### ISSUE THREAD

**Issue by otakustay** [ecomfe/spec#38]
使用[eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react)，已经包含所有规则的具体配置，可以针对每一个讨论

```js
{
    "default-props-match-prop-types": [2],
    "display-name": [2],
    "forbid-component-props": [1],
    "forbid-elements": [0],
    "forbid-foreign-prop-types": [1],
    "forbid-prop-types": [0],
    "jsx-boolean-value": [2],
    "jsx-closing-bracket-location": [2],
    "jsx-curly-spacing": [2],
    "jsx-equals-spacing": [2],
    "jsx-filename-extension": [2, [".js", ".jsx", ".es"]],
    "jsx-first-prop-new-line": [2],
    "jsx-handler-names": [1, {"eventHandlerPrefix": "", "eventHandlerPropPrefix": "on"}],
    "jsx-indent-props": [2, 4],
    "jsx-indent": [2, 4],
    "jsx-key": [2],
    "jsx-max-props-per-line": [2, {"when": "multiline", "maximum": 1}],
    "jsx-no-bind": [1],
    "jsx-no-comment-textnodes": [1],
    "jsx-no-duplicate-props": [2],
    "jsx-no-literals": [2],
    "jsx-no-target-blank": [2],
    "jsx-no-undef": [2],
    "jsx-pascal-case": [2],
    "jsx-sort-props": [0],
    "jsx-space-before-closing": [2],
    "jsx-tag-spacing": [2],
    "jsx-uses-react": [0],
    "jsx-uses-vars": [2],
    "jsx-wrap-multilines": [2],
    "no-array-index-key": [2],
    "no-children-prop": [2],
    "no-danger-with-children": [2],
    "no-danger": [1],
    "no-deprecated": [2],
    "no-did-mount-set-state": [2],
    "no-did-update-set-state": [2],
    "no-direct-mutation-state": [2],
    "no-find-dom-node": [2],
    "no-is-mounted": [2],
    "no-multi-comp": [2, {"ignoreStateless": true}],
    "no-render-return-value": [2],
    "no-set-state": [0],
    "no-string-refs": [2],
    "no-unescaped-entities": [2],
    "no-unknown-property": [2],
    "no-unused-prop-types": [1],
    "no-will-update-set-state": [2],
    "prefer-es6-class": [2],
    "prefer-stateless-function": [2],
    "prop-types": [2],
    "react-in-jsx-scope": [0],
    "require-default-props": [2],
    "require-optimization": [0],
    "require-render-return": [2],
    "self-closing-comp": [2],
    "sort-prop-types": [0],
    "style-prop-object": [2],
    "void-dom-elements-no-children": [2],
    "sort-comp": [
        2,
        {
            "order": [
                "static-properties",
                "static-methods",
                "lifecycle",
                "everything-else",
                "render"
            ],
            "groups": [
                "static-properties": [
                    "displayName",
                    "propTypes",
                    "contextTypes",
                    "childContextTypes",
                    "mixins",
                    "statics"
                ],
                "lifecycle": [
                    "defaultProps",
                    "constructor",
                    "getDefaultProps",
                    "getInitialState",
                    "state",
                    "getChildContext",
                    "componentWillMount",
                    "componentDidMount",
                    "componentWillReceiveProps",
                    "shouldComponentUpdate",
                    "componentWillUpdate",
                    "componentDidUpdate",
                    "componentWillUnmount"
                ]
            ]
        }
    ]
}
```

**Comment by chriswong** [comment]
7.0.1 上发布的已经没有 default-props-match-prop-types 了，repo 上还能看到

**Comment by chriswong** [comment]
fecs react 分支也加了插件配置，跟你的这个配置要对一下

**Comment by otakustay** [comment]
整理了不一样的地方：

|规则|fecs|spec|
|--|--|--|
|display-name|0|2|
|forbid-prop-types|1|0|
|jsx-filename-extension|0|[2, [".js", ".jsx", ".es"]]|
|jsx-handler-names|[2, {"eventHandlerPrefix": "on", "eventHandlerPropPrefix": "on"}]|[2, {"eventHandlerPropPrefix": "on"}]|
|jsx-key|1|2|
|jsx-no-bind|[2, {"ignoreRefs": true}]|2|
|jsx-no-comment-textnodes|2|1|
|jsx-no-duplicate-props|[2, {"ignoreCase": true}]|2|
|jsx-no-literals|0|2|
|jsx-no-target-blank|1|2|
|jsx-no-undef|[2, {"allowGlobals": true}]|2|
|jsx-space-before-closing|?|2|
|no-danger-with-children|0|2|
|no-danger|2|1|
|no-deprecated|1|2|
|no-string-refs|1|2|
|no-unused-prop-types|2|1|
|prop-types|1|2|
|require-default-props|0|2|
|self-closing-comp|[2, {"component": true, "html": false}]|2|
|sort-comp|2|[2, ...]|
|no-useless-constructor|1|?|

**Comment by otakustay** [comment]
对照上面的不同，做下基本的解释：

- `display-name`：检查的只是`createClass`，首先我们就反对这种形式，其次既然你用这个API就应该给`displayName`
- `forbid-prop-types`：同意应该用warning
- `jsx-filename-extension`：为了fecs能检查到，反正不是这些后缀fecs也检查不到
- `jsx-handler-names`：不一样的是`eventHandlerPrefix`，我认为一个class中的方法不应该表达“自己是处理事件的”这一点，而是表达“完成什么样的业务逻辑”，所以用`on`或者`handle`为前缀并不合适，具体交由团队来决定就好
- `jsx-key`：这个是react很重要的功能，开着比较好
- `jsx-no-bind`：没考虑到ref的问题，所以同意使用`ignoreRefs: true`
- `jsx-no-comment-textnodes`：应该编译期能解决掉的事情，感觉不一定要error
- `jsx-no-duplicate-props`：同意`ignoreCase: true`
- `jsx-no-literals`：感觉挺有用的，literal确实没必要写在代码块中
- `jsx-no-target-blank`：`noopener noreferrer`不仅在安全性上重要，在性能上也有帮助（打开新窗口会快一些），因此打开这个规则，如果有人真的要的话自己写注释禁用吧
- `jsx-no-undef`：能用react的工程已经是现代化工程了，没有理由不用模块化而用全局变量，所以没必要开`allowGlobals: true`给他们
- `jsx-space-before-closing`：fecs现在的配置里没有这条
- `no-danger-with-children`：本身react就不允许，那么fecs能检查出来是最好的
- `no-danger`：因为这种情况肯定是少之又少的，所以开到最大，有必要的时候让他们自己注释禁用
- `no-deprecated`：会标deprecated的肯定是写代码的人，给他们他错误让改掉挺好的吧
- `no-string-refs`：这个功能react以后可能会干掉，所以别留着了
- `no-unused-prop-types`：同意开到error
- `prop-types`：从公司对代码质量的角度来说，应该要有，开到error在icode报错有必要
- `require-default-props`：同上
- `self-closing-comp`：没考虑到HTML的，同意`{html: false}`
- `sort-comp`：用我这边定义的顺序就行

**Comment by chriswong** [comment]
jsx-space-before-closing 已经 deprecated 了

**Comment by chriswong** [comment]
js-pascal-case 的 allowAllCaps 改为 true
