### ISSUE TITLE
关于 “[强制]没有子节点的非DOM组件使用自闭合语法”

### ISSUE THREAD

**Issue by errorrik** [ecomfe/spec#43]
描述如下：

> 对于DOM节点，按照HTML编码规范相关规则进行闭合，其中void element使用自闭合语法。

我理解void element不用闭合吧？这和我们 《html style guide》 冲突了

https://github.com/ecomfe/spec/blob/master/html-style-guide.md#强制-对于无需自闭合的标签不允许自闭合

**Comment by otakustay** [comment]
jsx必须闭合，否则是语法错误，所以这个没啥能讨论的，我先关了
