### ISSUE TITLE
[强制] 当文件无法使用 .js 扩展名时，使用 .es 扩展名。

### ISSUE THREAD

**Issue by DualWield** [ecomfe/spec#49]
这个强制能不能改成建议？

**Comment by otakustay** [comment]
原因？

**Comment by DualWield** [comment]
原因现在百度云的js代码很多都是es6扩展名，没有办法过代码审核

**Comment by hax** [comment]
哈哈，`es6`的文件名明显有歧义啊。难道这些文件都不能使用es7+的新特性？

**Comment by DualWield** [comment]
@hax 历史原因，确实是一个问题

**Comment by otakustay** [comment]
> 原因现在百度云的js代码很多都是es6扩展名，没有办法过代码审核

你这个理由有点过分了啊

> 哈哈，es6的文件名明显有歧义啊。难道这些文件都不能使用es7+的新特性？

yes，其实我不是想问个理由，合理的我觉得应该是`.js`、`.mjs`、`.es`，不允许`.jsx`

**Comment by leeight** [comment]
@DualWield 我记得现在的情况是 `.es6` 后缀的文件，icode 根本不检查的耶，所以为啥会出现 `没有办法过代码审核` 的问题呢？

**Comment by DualWield** [comment]
@leeight 现在是这样的。我们想在本地的pre-commit的时候做一些代码检查，如果不过的话不让提交，现在做不了因为有这个报错

**Comment by otakustay** [comment]
```
fecs src/**/*.es6 --type=js
```

这样可以吗？

**Comment by leeight** [comment]
或者修改 `.fecsrc` 的配置文件，添加

```
{
  "eslint": {
    ...
    "rules": {
      "fecs-esnext-ext": "es6"
    }
    ...
  }
}
```

**Comment by DualWield** [comment]
@leeight 赞~
