### ISSUE TITLE
对象常量的属性名要全部大写吗？

### ISSUE THREAD

**Issue by juntaoshuai** [ecomfe/spec#57]
export const TASK_TYPE = {
  DISPATCH: 1, 
  AUTONOMIC: 2, 
  FIXED: 3
}
对象常量是像上面那样写： 属性名也大写吗？

**Comment by otakustay** [comment]
没有这一要求，属性名也全大写的是枚举。一个对象是否属于枚举，由其业务属性决定

**Comment by juntaoshuai** [comment]
export const TASK_TYPE = {
    dispatch: 1,
     autonomic: 2,
     fixed: 3
}
那就这样，属性名小写，像变量规则一样吗？？？

**Comment by otakustay** [comment]
属性名正常情况下使用camelCase即可，与变量名规则相同
